services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      MSSQL_SA_PASSWORD: "Za3em445439!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_api
    image: za3em/movie-api:latest
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__MyConnection: "Server=sqlserver,1433;Database=MovieDb;User Id=sa;Password=Za3em445439!;TrustServerCertificate=True;Encrypt=False;"
      ASPNETCORE_URLS: "http://+:8080"