version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrong@Pass123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  movieapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movieapp
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver